# -*- coding: utf-8 -*-
"""Write docs/TESTING.md from the tests themselves and the sabotage plans.

    python scripts/catalogue.py            # rewrite docs/TESTING.md
    python scripts/catalogue.py --check    # fail if it is out of date (CI)

Every test name in this project is the sentence stating what it proves, so
the catalogue is generated rather than kept by hand: a hand-kept catalogue
drifts, as the ITSaNAS one did. Each test is listed with the sabotage
defences (scripts/sabotage/*.json) that must turn it red.
"""
import glob
import io
import json
import os
import re
import sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
TARGET = os.path.join(ROOT, 'docs', 'TESTING.md')

HEADER = """# Test catalogue

Generated by `python scripts/catalogue.py` from the test files and the
sabotage plans; CI fails when it is out of date. Every test name states the
property it proves.

## Rules

- **Red before green, mostly.** A test is committed failing (`red:` commit)
  before the code that makes it pass (`green:` commit). Not always: the
  evidence, guard, rules and web modules and red-team pass 2 (commits
  6478449, 49ca041, 2f27eb4, 2bd13b7, b0f0162, d605261, 44f289f) brought
  their tests with their code; what proves those tests bite is sabotage.
- **Sabotage-verified.** Each rule that matters has a defence in
  `scripts/sabotage/*.json`: the line to break and the tests that must go red.
  `python scripts/sabotage.py` breaks each one, checks those tests fail,
  restores the file from a byte-for-byte copy. The last column names the
  defences that cover each test; "—" means none does (yet).
- **No personal data.** Tests use `test/fixtures/profile.synthetic.json`, a
  fictitious person. The real profile never enters the repository.
"""


def tests_by_file():
    found = []
    for path in sorted(glob.glob(os.path.join(ROOT, 'test', '*.test.js'))):
        text = io.open(path, encoding='utf-8').read()
        # A name may hold its own quote, escaped: 'the run\'s files'.
        names = re.findall(r"^test\((['\"])((?:\\.|(?!\1).)*)\1,", text, re.M)
        found.append((os.path.basename(path), [re.sub(r"\\(.)", r"\1", name) for _, name in names]))
    return found


def defences_by_test():
    covering = {}
    for path in sorted(glob.glob(os.path.join(ROOT, 'scripts', 'sabotage', '*.json'))):
        plan = json.load(io.open(path, encoding='utf-8'))
        for defence, spec in plan['defences'].items():
            for test in spec.get('expect', []):
                covering.setdefault(test, []).append(defence)
    return covering


def render():
    covering = defences_by_test()
    lines = [HEADER]
    total = 0
    for filename, names in tests_by_file():
        lines.append('## `test/%s`\n' % filename)
        lines.append('| Property (the test name) | Sabotage defences |')
        lines.append('|---|---|')
        for name in names:
            total += 1
            defences = '; '.join(covering.get(name, [])) or '—'
            lines.append('| %s | %s |' % (name.replace('|', '\\|'), defences))
        lines.append('')
    defended = sum(1 for _, names in tests_by_file() for name in names if name in covering)
    lines.append('**%d tests, %d of them covered by at least one sabotage defence.**\n' % (total, defended))
    unknown = sorted(set(covering) - {name for _, names in tests_by_file() for name in names})
    if unknown:
        lines.append('Defences naming a test that does not exist: %s\n' % ', '.join(unknown))
    return '\n'.join(lines)


def main():
    content = render()
    if '--check' in sys.argv:
        current = io.open(TARGET, encoding='utf-8').read() if os.path.exists(TARGET) else ''
        if current != content:
            print('docs/TESTING.md is out of date: run python scripts/catalogue.py')
            return 1
        print('docs/TESTING.md is up to date')
        return 0
    io.open(TARGET, 'w', encoding='utf-8', newline='\n').write(content)
    print('docs/TESTING.md written')
    return 0


if __name__ == '__main__':
    sys.exit(main())
